cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove')
]

drug/urls.py
from django.conf.urls import url
from drug.views import (
    category,
    add_drug,
    view_drug,
    manage_drug,
    delete,
)

urlpatterns = [
    url(r'^$', category, name='category'),
    url(r'^(?P<key>[\d])/delete/$', delete, name='delete'),
    url(r'^add/$', add_drug, name='add_drug'),
    url(r'^view/$', view_drug, name='view_drug'),
    url(r'^manage/$', manage_drug, name='manage_drug'),
]

pharmacy/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('staff.urls', namespace='staff')),
    url(r'^sale/', include('sale.urls', namespace='sale')),
    url(r'^drug/', include('drug.urls', namespace='drug')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
]

drug/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.
TEMP = (('Cool Area', 'Cool Area'),
        ('Dry Area', 'Dry Area'),
        ('Warm Area', 'Warm Area')
        )


class DrugCategory(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('sale:sale')


class Drug(models.Model):
    batch_no = models.CharField(max_length=100)
    drug_name = models.CharField(max_length=200)
    manufacture = models.CharField(max_length=200)
    category = models.ForeignKey(DrugCategory, on_delete=models.CASCADE)
    temperature = models.CharField(max_length=100, choices=TEMP)
    quantity = models.IntegerField(default=0)
    cost_price = models.IntegerField(default=0)
    production_date = models.DateField()
    expiry_date = models.DateField()
    total_cost = models.IntegerField()
    price_per_item = models.IntegerField()
    drug_location = models.CharField(max_length=500)
    visible = models.BooleanField(default=True)

    def __str__(self):
        return self.drug_name

drug/forms.py
from django import forms

from drug.models import DrugCategory, Drug


class CategoryForm(forms.ModelForm):
    class Meta:
        model = DrugCategory
        fields = ('name', )


class DrugForm(forms.ModelForm):
    class Meta:
        model = Drug
        fields = (
            'batch_no', 'drug_name', 'manufacture',
            'category', 'temperature', 'quantity', 'cost_price',
            'production_date', 'expiry_date', 'total_cost',
            'price_per_item', 'drug_location'
        )

drug/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import (
    render,
    redirect,
    HttpResponseRedirect,
    get_object_or_404,
)
from django.urls import reverse

from drug.forms import (
    CategoryForm,
    DrugForm,
)
from drug.models import (
    DrugCategory,
    Drug,
)
from utils import get_user


# Create your views here.


@login_required(login_url='/?next=/')
def category(request):
    user = get_user(request.user)
    if not user.is_admin:
        return redirect('/not-found')
    user = get_user(request.user)
    if not user.is_admin:
        return redirect('/not-found')
    form = CategoryForm(request.POST or None)
    if form.is_valid():
        if form.is_valid():
            name = form.cleaned_data['name']
            DrugCategory.objects.create(name=name)
            messages.success(request, 'sucessuflly add new category')
            return HttpResponseRedirect(reverse('drug:category'))
    context = {
        'categories': DrugCategory.objects.all(),
        'form': form,
        'user': get_user(request.user),
    }
    return render(request, "drug/add_category.html", context)


@login_required(login_url='/?next=/')
def add_drug(request):
    user = get_user(request.user)
    if not user.is_admin:
        return redirect('/not-found')
    form = DrugForm(request.POST or None)
    if form.is_valid():
        if form.is_valid():
            batch_no = form.cleaned_data['batch_no']
            drug_name = form.cleaned_data['drug_name']
            manufacture = form.cleaned_data['manufacture']
            temperature = form.cleaned_data['temperature']
            quantity = form.cleaned_data['quantity']
            cat = form.cleaned_data['category']
            cost_price = form.cleaned_data['cost_price']
            production_date = form.cleaned_data['production_date']
            expiry_date = form.cleaned_data['expiry_date']
            total_cost = form.cleaned_data['total_cost']
            price_per_item = form.cleaned_data['price_per_item']
            drug_location = form.cleaned_data['drug_location']

            Drug.objects.create(
                batch_no=batch_no, drug_name=drug_name, manufacture=manufacture,
                category=cat, temperature=temperature, quantity=quantity,
                cost_price=cost_price, production_date=production_date,
                expiry_date=expiry_date, total_cost=total_cost,
                price_per_item=price_per_item, drug_location=drug_location
            )
            return HttpResponseRedirect(reverse('drug:view_drug'))
    context = {
        'categories': DrugCategory.objects.all(),
        'form': form,
        'user': get_user(request.user),
    }
    return render(request, "drug/add_drug.html", context)


@login_required(login_url='/?next=/')
def view_drug(request):
    product = Drug.objects.all()
    context = {
        'products': product,
        'user': get_user(request.user),
    }
    return render(request, 'drug/view_drugs.html', context)


@login_required(login_url='/?next=/')
def manage_drug(request):
    user = get_user(request.user)
    if not user.is_admin:
        return redirect('/not-found')
    drug = Drug.objects.all()
    context = {
        'products': drug,
        'user': get_user(request.user),
    }
    return render(request, 'drug/manage_drug.html', context)


@login_required(login_url='/?next=/')
def delete(request, key):
    user = get_user(request.user)
    if not user.is_admin:
        return redirect('/not-found')
    drug = get_object_or_404(Drug, id=key)
    drug.visible = False
    drug.save()
    context = {
        'products': Drug.objects.all(),
        'user': get_user(request.user),
    }
    return render(request, 'drug/manage_drug.html', context)

templates/drug/add_category.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %}Add Category{% endblock %}

{% block stylesheets %}
    {{ block.super }}

    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block right_coln %}
<!-- Right side column. Contains the navbar and content of the page -->
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Add Categories</h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-6">
      <!-- general form elements -->
      <div class="box box-primary">
        <!-- form start -->
      {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert-dismissable">
                        <h2><b>✖{{ message|safe }}</b></h2>
                    </div>
                {% else %}
                    <div class="alert-dismissible">
                        <h2><b>{{ message|safe }}</b></h2>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        <form role="form" method="post">{% csrf_token %}
          <div class="box-body">
            <div class="form-group">
              <label for="nwcat">New Category</label>
              {{ form.name | add_class:"form-control" |attr:'class: form-control' | append_attr:'id:nwcat' | append_attr:'placeholder:New DrugCategory'}}
            </div>

            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Add</button>
            </div>
          </div>
        </form>
        <!-- select -->
          <div class="form-group">
              <label>All Categories</label>
              <select class="form-control">
              <option>--------------</option>
                  {% for category in categories %}
                      <option>{{ category.name }}</option>
                  {% endfor %}
              </select>
          </div>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    <!-- right column -->
  </div>   <!-- /.row -->
</section><!-- /.content -->
</div><!-- /.content-wrapper -->
{% endblock %}

{% block javascripts %}
    {{ block.super }}
    <!-- FastClick -->
    <script src='{% static 'plugins/fastclick/fastclick.min.js'%}'></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}" type="text/javascript"></script>
{% endblock %}

templates/drug/add_drug.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %}Add Drug{% endblock %}

{% block stylesheets %}
    {{ block.super }}
    <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block right_coln %}
  <!-- Right side column. Contains the navbar and content of the page -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Mujahid Pharmacy and Store
        <small>ADD DRUGS</small>
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header">
              <h3 class="box-title">Drugs Details</h3>
            </div><!-- /.box-header -->
            <!-- form start -->
            <form role="form" method="post">{% csrf_token %}
              <div class="box-body">
                <div class="form-group has-feedback col-md-6">
                    <label for="batch">batch no.</label>
                    {{ form.batch_no | add_class:"form-control" | attr:'placeholder:BATCH NO' | append_attr:'id:batch' }}
                </div>
                <div class="form-group col-md-6">
                  <label for="drugn">Drug Name</label>
                    {{ form.drug_name | add_class:"form-control" | attr:'placeholder:Drug Name' | append_attr:'id:DRUGN' }}
                </div>
                <div class="form-group col-md-6">
                  <label for="manuf">Manufacture</label>
                    {{ form.manufacture | add_class:"form-control" | attr:'placeholder:Manufacture' | append_attr:'id:manuf' }}
                  </div>
                  <!-- select -->
                  <div class="form-group col-md-6">
                      <label>Drud Category</label>
                      {{ form.category | add_class:"form-control"  }}
                  </div>
                  <div class="form-group col-md-6">
                      <label>Drud Tempreture</label>
                        {{ form.temperature | add_class:"form-control"  }}
                  </div>
                  <div class="form-group col-md-6">
                      <label for="qunt">Quantity</label>
                      {{ form.quantity | add_class:"form-control" | attr:'placeholder:Quantity' | append_attr:'id:QUNT' }}
                  </div>
                <div class="form-group col-md-6">
                  <label for="cost">Cost Price</label>
                    {{ form.cost_price | add_class:"form-control" | attr:'placeholder:Cost Price' | append_attr:'id:cost' }}
                </div>
                <div class="form-group col-md-6">
                  <label for="dop">Production Date</label>
                    {{ form.production_date | add_class:"form-control" | attr:'placeholder:yyyy-mmm-dd' | append_attr:'id:dop'  }}
                </div>
                <div class="form-group col-md-6">
                  <label for="doe">Expiry date</label>
                    {{ form.expiry_date | add_class:"form-control" | attr:'placeholder:yyyy-mm-dd' | append_attr:'id:doe' }}
                </div>
                <div class="form-group col-md-6">
                  <label for="tcost">Total Cost</label>
                    {{ form.total_cost | add_class:"form-control" | attr:'placeholder:Total Cost' | append_attr:'id:tcost' }}
                  </div>
                <div class="form-group col-md-6">
                  <label for="price">Price per item</label>
                  {{ form.price_per_item | add_class:"form-control" | attr:'placeholder:Price per item' | append_attr:'id:price' }}
                </div>
                <div class="form-group col-md-6">
                  <label for="dloc">Drug Location</label>
                    {{ form.drug_location | add_class:"form-control" | attr:'placeholder:Drug Location' | append_attr:'id:dloc' }}
                </div>
              </div><!-- /.box-body -->

              <div class="box-footer" align="center">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-primary">Cancel</button>
              </div>
              <div>
          </div><!-- /.box -->
              </form>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
      </div>   <!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->


{% endblock %}
{% block javascripts %}
    {{ block.super }}
    <!-- FastClick -->
    <script src='{% static 'plugins/fastclick/fastclick.min.js' %}'></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}" type="text/javascript"></script>
{% endblock %}

templates/drug/manage_drug.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block title %}View Drug{% endblock %}

{% block stylesheets %}
    {{ block.super }}
    <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- DATA TABLES -->
    <link href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block right_coln %}
  <!-- Right side column. Contains the navbar and content of the page -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        List of Drugs Available
      </h1>
    </section>

    <div class="box">
      <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
          <tr>
            <td>Batch NO.</td>
            <td>Drug Name</td>
            <td>Manufacture</td>
            <td>Expire Date</td>
            <td>Production Date</td>
            <td>Category</td>
            <td>Temperature</td>
            <td>Cost Price</td>
            <td>Quantity</td>
            <td>Price per item</td>
            <td>Registration Date</td>
            <td>Total Cost</td>
            <td>Drug Location</td>
            <td>Action</td>
          </tr>
          </thead>
          <tbody>
                {% for product in products %}
                    {% if product.visible %}
                      <tr>
                        <td>{{ product.batch_no }}</td>
                        <td>{{ product.product_name }}</td>
                        <td>{{ product.manufacture }}</td>
                        <td>{{ product.expiry_date }}</td>
                        <td>{{ product.production_date }}</td>
                        <td>{{ product.category }}</td>
                        <td>{{ product.temperature }}</td>
                        <td>{{ product.cost_price }}</td>
                        <td>{{ product.quantity }}</td>
                        <td>{{ product.price_per_item }}</td>
                        <td>{{ product.production_date }}</td>
                        <td>{{ product.total_cost }}</td>
                        <td>{{ product.product_location }}</td>
                        <td><a href="{% url 'drug:delete' product.id %}"> <button type="button">Delete</button></a></td>
                      </tr>
                    {% endif %}
                {% endfor %}
          </tbody>
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div><!-- /.col -->
{% endblock %}

{% block javascripts %}
    {{ block.super }}
<!-- DATA TABES SCRIPT -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.js' %}" type="text/javascript"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.js' %}" type="text/javascript"></script>
    <!-- SlimScroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='{% static 'plugins/fastclick/fastclick.min.js' %}'></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}" type="text/javascript"></script>
    <!-- page script -->
    <script type="text/javascript">
      $(function () {
        $("#example1").dataTable();
        $('#example2').dataTable({
          "bPaginate": true,
          "bLengthChange": false,
          "bFilter": false,
          "bSort": true,
          "bInfo": true,
          "bAutoWidth": false
        });
      });
    </script>
{% endblock %}

templates/drug/view_drugs.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block title %}View product{% endblock %}

{% block stylesheets %}
    {{ block.super }}
    <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- DATA TABLES -->
    <link href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block right_coln %}
  <!-- Right side column. Contains the navbar and content of the page -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Data Tables
        <small>advanced tables</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Data tables</li>
      </ol>
    </section>

          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <td>Batch NO.</td>
                    <td>product Name</td>
                    <td>Manufacture</td>
                    <td>Expire Date</td>
                    <td>Production Date</td>
                    <td>Category</td>
                    <td>Temperature</td>
                    <td>Cost Price</td>
                    <td>Quantity</td>
                    <td>Price per item</td>
                    <td>Registration Date</td>
                    <td>Total Cost</td>
                    <td>product Location</td>
                  </tr>
                </thead>
                <tbody>
                {% for product in products %}
                    {% if product.visible %}
                      <tr>
                        <td>{{ product.batch_no }}</td>
                        <td>{{ product.product_name }}</td>
                        <td>{{ product.manufacture }}</td>
                        <td>{{ product.expiry_date }}</td>
                        <td>{{ product.production_date }}</td>
                        <td>{{ product.category }}</td>
                        <td>{{ product.temperature }}</td>
                        <td>{{ product.cost_price }}</td>
                        <td>{{ product.quantity }}</td>
                        <td>{{ product.price_per_item }}</td>
                        <td>{{ product.production_date }}</td>
                        <td>{{ product.total_cost }}</td>
                        <td>{{ product.product_location }}</td>
                      </tr>
                    {% endif %}
                {% endfor %}
              </tbody>
              </table>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
        </div><!-- /.col -->
{% endblock %}

{% block javascripts %}
    {{ block.super }}
    <!-- DATA TABES SCRIPT -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.js' %}" type="text/javascript"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.js' %}" type="text/javascript"></script>
    <!-- SlimScroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='{% static 'plugins/fastclick/fastclick.min.js' %}'></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}" type="text/javascript"></script>
    <!-- page script -->
    <script type="text/javascript">
      $(function () {
        $("#example1").dataTable();
        $('#example2').dataTable({
          "bPaginate": true,
          "bLengthChange": false,
          "bFilter": false,
          "bSort": true,
          "bInfo": true,
          "bAutoWidth": false
        });
      });
    </script>
{% endblock %}