cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove')
]

drug/urls.py
from django.conf.urls import url
from drug.views import (
    category,
    add_drug,
    view_drug,
    manage_drug,
    delete,
)

urlpatterns = [
    url(r'^$', category, name='category'),
    url(r'^(?P<key>[\d])/delete/$', delete, name='delete'),
    url(r'^add/$', add_drug, name='add_drug'),
    url(r'^view/$', view_drug, name='view_drug'),
    url(r'^manage/$', manage_drug, name='manage_drug'),
]

pharmacy/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('staff.urls', namespace='staff')),
    url(r'^sale/', include('sale.urls', namespace='sale')),
    url(r'^drug/', include('drug.urls', namespace='drug')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
]

sale/urls.py
from django.conf.urls import url
from views import (
    view_sale,
    sale_detail,
    sale,
    GeneratePDF
)

urlpatterns = [
    url(r'^$', sale,  name='sale'),
    url(r'^view/$', view_sale, name='view_sale'),
    url(r'^(?P<order>\d+).pdf/$', GeneratePDF.as_view(), name='pdf'),
    url(r'^(?P<key>\d+)/$', sale_detail, name='sale_detail'),
]

staff/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout
from views import (
    register,
    add_employee,
    registered_staff,
    view_staff,
    default,
    login_view,
    not_found,
    delete,
)
urlpatterns = [
    url(r'^$', login_view, name='login'),
    url(r'^default/$', default, name='default'),
    url(r'^log/$', logout, {'template_name': 'logout.html'}, name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^not-found/$', not_found, name='not_found'),
    url(r'^add-employee/$', add_employee, name='add_employee'),
    url(r'^registered-staffs/$', registered_staff, name='registered_staff'),
    url(r'^view-staff/$', view_staff, name='view_staff'),
    url(r'^(?P<key>[\d])/delete/$', delete, name='delete'),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
        {% block meta %}
            <meta charset="UTF-8">
            <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        {% endblock meta %}

        <title>
            {% block title %}{% endblock title %}
        </title>

        {% block stylesheets %}
            <!-- Bootstrap 3.3.2 -->
            <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
            <!-- Font Awesome Icons -->
            <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
            <!-- Theme style -->
            <link href="{% static 'dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
            <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
            <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
            <!--[if lt IE 9]>
                <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
                <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
            <![endif]-->
        {% endblock stylesheets %}

    {% endblock head %}
</head>


{% block body %}
    <body class="skin-blue">
        <div class="wrapper">
            {% block nav %}
                {% include 'base/nav.html' %}
            {% endblock %}
            {% block right_coln %}

            {% endblock right_coln %}

            <footer class="main-footer">
              <div class="pull-right hidden-xs">
                <b>Version</b> 2.0
              </div>
              <strong>Copyright &copy; {{ today|date:'Y' }} <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.
            </footer>
        </div>

        {% block javascripts %}
            <!-- jQuery 2.1.3 -->
            <script src="{% static 'plugins/jQuery/jQuery-2.1.3.min.js' %}"></script>
            <!-- Bootstrap 3.3.2 JS -->
            <script src="{% static 'bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
        {% endblock javascripts %}
    </body>
{% endblock body %}
</html>

templates/base/default_page.html
{% extends 'base/base.html' %}
{% load staticfiles %}
    {% block stylesheets %}
        {{ block.super }}
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />

    <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'plugins/iCheck/flat/blue.css' %}" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="{% static 'plugins/morris/morris.css' %}" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet" type="text/css" />
    <!-- Date Picker -->
    <link href="{% static 'plugins/datepicker/datepicker3.css' %}" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="{% static 'plugins/daterangepicker/daterangepicker-bs3.css' %}" rel="stylesheet" type="text/css" />
    <!-- bootstrap wysihtml5 - text editor -->
    <link href="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}" rel="stylesheet" type="text/css" />
    {% endblock stylesheets %}

{% block right_coln %}
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            MUJAHID PHARMACY AND STORES
            <small>Lafiya Jarice</small>
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Small boxes (Stat box) -->
          <div class="row">
            <div class="col-lg-{% if user.is_admin %}3{% else %}6{% endif %} col-xs-6">
              <!-- small box -->
              <div class="small-box bg-aqua">
                <div class="inner">
                  <h3>{{ drugs.count }}</h3>
                  <p>Total Drugs</p>
                </div>
                <div class="icon">
                  <i class="ion ion-bag"></i>
                </div>
                <a href="{% url 'drug:manage_drug' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-{% if user.is_admin %}3{% else %}6{% endif %} col-xs-6">
              <!-- small box -->
              <div class="small-box bg-green">
                <div class="inner">
                    <h3>{{ expired }}</h3>
                  <p>Expired Drugs</p>
                </div>
                <div class="icon">
                  <i class="ion ion-stats-bars"></i>
                </div>
                <a href="{% url 'drug:manage_drug' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
          {% if user.is_admin %}
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-yellow">
                <div class="inner">
                  <h3>{{ sale.count }}</h3>
                  <p>total Sales</p>
                </div>
                <div class="icon">
                  <i class="fa fa-th-large"></i>
                </div>
                <a href="{% url 'sale:sale' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-red">
                <div class="inner">
                  <h3>{{ staff.count }}</h3>
                  <p>Staff Record</p>
                </div>
                <div class="icon">
                  <i class="fa fa-warning"></i>
                </div>
                <a href="{% url 'staff:registered_staff' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
          {% endif %}
          </div><!-- /.row -->
          <!-- Main row -->
          <div class="row">
            <!-- Left col -->
            <section class="col-lg-12 connectedSortable">
              <!-- Custom tabs (Charts with tabs)-->

              <!-- quick email widget -->
              <div class="box box-info">
                <div class="box-header">
                  <i class="fa fa-envelope"></i>
                  <h3 class="box-title">Quick Email</h3>
                  <!-- tools box -->
                  <div class="pull-right box-tools">
                    <button class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
                  </div><!-- /. tools -->
                </div>
                <div class="box-body">
                  <form action="#" method="post">
                    <div class="form-group">
                      <input type="email" class="form-control" name="emailto" placeholder="Email to:"/>
                    </div>
                    <div class="form-group">
                      <input type="text" class="form-control" name="subject" placeholder="Subject"/>
                    </div>
                    <div>
                      <textarea class="textarea" placeholder="Message" style="width: 100%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                    </div>
                  </form>
                </div>
                <div class="box-footer clearfix">
                  <button class="pull-right btn btn-default" id="sendEmail">Send <i class="fa fa-arrow-circle-right"></i></button>
                </div>
              </div>

            </section><!-- /.Left col -->
          </div><!-- /.row (main row) -->

        </section><!-- /.content -->
      </div>

{% endblock %}

{% block javascripts %}

    {{ block.super }}

    <!-- jQuery UI 1.11.2 -->
    <script src="http://code.jquery.com/ui/1.11.2/jquery-ui.min.js" type="text/javascript"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Morris.js charts -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="{% static 'plugins/morris/morris.min.js' %}" type="text/javascript"></script>
    <!-- Sparkline -->
    <script src="{% static 'plugins/sparkline/jquery.sparkline.min.js' %}" type="text/javascript"></script>
    <!-- jvectormap -->
    <script src="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}" type="text/javascript"></script>
    <!-- jQuery Knob Chart -->
    <script src="{% static 'plugins/knob/jquery.knob.js' %}" type="text/javascript"></script>
    <!-- daterangepicker -->
    <script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}" type="text/javascript"></script>
    <!-- datepicker -->
    <script src="{% static 'plugins/datepicker/bootstrap-datepicker.js' %}" type="text/javascript"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="{% static 'plugins/iCheck/icheck.min.js' %}" type="text/javascript"></script>
    <!-- Slimscroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
    <!-- FastClick -->
    <script src="{% static 'plugins/fastclick/fastclick.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>

    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'dist/js/pages/dashboard.js' %}" type="text/javascript"></script>

    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}" type="text/javascript"></script>
    <script>
        new Vue({
            el: 'app',
            data:{
                url: 'https://www.google.com',
                url_2: 'pages/forms/add_drug.html'
            }


        });
    </script>
    <script src="{% static 'vue.js' %}"></script>
    <script src="{% static 'vue_details.js' %}" type="text/javascript"></script>
{% endblock %}

templates/base/nav.html
{% load staticfiles %}
<header class="main-header">
      <!-- Logo -->
      <a href="{% url 'staff:default' %}" class="logo">
        <b>
            {% if user.is_admin %}
                Admin
            {% else %}
                Staff
            {% endif %}
        </b>Page</a>
      <!-- Header Navbar: style can be found in header.less -->
      <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
          <span class="sr-only">Toggle navigation</span>
        </a>
      </nav>
</header>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- search form
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
          </span>
      </div>
    </form>
    /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-files-o"></i>
          <span>Drug Options</span>
        </a>
        <ul class="treeview-menu">
            {% if user.is_admin %}
          <li><a href="{% url 'drug:add_drug' %}"><i class="fa fa-circle-o"></i>Add Drug</a></li>
            <li><a href="{% url 'drug:category' %}"><i class="fa fa-circle-o"></i>Add Category</a></li>
            {% endif %}
          <li><a href="{% url 'drug:view_drug' %}"><i class="fa fa-circle-o"></i>View Drug</a></li>
          {% if user.is_admin %}
            <li><a href="{% url 'drug:manage_drug' %}"><i class="fa fa-circle-o"></i>Manage Drug</a></li>
        {% endif %}
        </ul>
      </li>
    {% if user.is_admin %}
      <li class="treeview">
        <a href="#">
          <i class="fa fa-laptop"></i>
          <span>Staff Information</span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li><a href="{% url 'staff:add_employee' %}"><i class="fa fa-circle-o"></i> Add Employee</a></li>
          <li><a href="{% url 'staff:view_staff' %}"><i class="fa fa-circle-o"></i>View Staff</a></li>
          <li><a href="{% url 'staff:registered_staff' %}"><i class="fa fa-circle-o"></i>View Registered Staff(s)</a></li>
        </ul>
      </li>
    {% endif %}
      <li class="treeview">
        <a href="#">
          <i class="fa fa-edit"></i> <span>Saless</span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li><a href="{% url 'sale:sale' %}"><i class="fa fa-circle-o"></i> Sales</a></li>
            {% if user.is_admin %}
          <li><a href="{% url 'sale:view_sale' %}"><i class="fa fa-circle-o"></i> General Sales</a></li>
            {% endif %}
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-folder"></i> <span>Details</span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          {% if user.is_admin %}
            <li><a href="{% url 'staff:register' %}"><i class="fa fa-circle-o"></i> Register New User</a></li>
            {% endif %}
            <li><a href="{% url 'staff:logout' %}"><i class="fa fa-circle-o"></i> Logout</a></li>
        </ul>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>