cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove')
]

pharmacy/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('staff.urls', namespace='staff')),
    url(r'^sale/', include('sale.urls', namespace='sale')),
    url(r'^drug/', include('drug.urls', namespace='drug')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
]

staff/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout
from views import (
    register,
    add_employee,
    registered_staff,
    view_staff,
    default,
    login_view,
    not_found,
    delete,
)
urlpatterns = [
    url(r'^$', login_view, name='login'),
    url(r'^default/$', default, name='default'),
    url(r'^log/$', logout, {'template_name': 'logout.html'}, name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^not-found/$', not_found, name='not_found'),
    url(r'^add-employee/$', add_employee, name='add_employee'),
    url(r'^registered-staffs/$', registered_staff, name='registered_staff'),
    url(r'^view-staff/$', view_staff, name='view_staff'),
    url(r'^(?P<key>[\d])/delete/$', delete, name='delete'),
]

staff/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

STATUE = (('Married', 'Married'), ('Single', 'Single'))
SEX = (('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'))

# Create your models here.


class Staffs(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_admin = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Employee(models.Model):
    name = models.CharField(max_length=100)
# passport = models.ImageField(blank=True)
    sex = models.CharField(max_length=20, choices=SEX)
    statue = models.CharField(max_length=20, choices=STATUE)
    date_of_birth = models.DateField(max_length=10)
    nationality = models.CharField(max_length=100)
    address = models.TextField()
    phone = models.IntegerField()
    email = models.EmailField(blank=True)
    date_employed = models.DateField()
    visible = models.BooleanField(default=True)

staff/forms.py
from django import forms
from staff.models import Employee
from django.shortcuts import get_object_or_404
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
    )
User = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'placeholder': 'User Name'}), label='User-name:')
    password = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}), label='Password:')


class RegisterForm(forms.Form):
    first_name = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'placeholder': 'First Name'}), label='First Name:')
    last_name = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'placeholder': 'Last Name'}), label='Last Name:')
    username = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'placeholder': 'Name'}), label='User Name:')
    password = forms.CharField(label='Password', required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}))
    is_admin = forms.BooleanField(required=False,)


class EmployeeForm(forms.ModelForm):

    class Meta:
        model = Employee
        fields = (
            'name', 'sex', 'statue', 'date_of_birth',
            'nationality', 'address', 'date_employed',
            'phone', 'email',
        )

staff/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import date

from django.contrib import messages
from django.contrib.auth import (
    login,
    authenticate,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)

from sale.models import ItemSale
from staff.forms import (
    RegisterForm,
    EmployeeForm,
    LoginForm,
)
from staff.models import (
    Staffs,
    Employee,
)
from drug.models import Drug
from utils import (
    get_user,
)


# Create your views here.


def login_view(request):
    next = request.GET.get('next')
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            if next:
                return redirect(next)
            return redirect('staff:default')
        messages.error(request, 'Username password does not match')
    return render(request, "base/registration/login.html", {"form": form})


def register(request):
    errors = {}
    next = request.GET.get('next')
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        user = User()
        is_admin = form.cleaned_data['is_admin']
        password = form.cleaned_data['password']
        user.username = form.cleaned_data['username']
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.set_password(password)
        try:
            user.save()
            Staffs.objects.create(user=user, is_admin=is_admin)
            login(request, user)
            if next:
                return redirect(next)
            return redirect("/")
        except Exception as e:
            errors = {

                'message': e
            }

    context = {
        "form": form,
        'errors': errors,
    }
    return render(request, 'base/registration/register.html', context)


@login_required(login_url='/?next=/')
def default(request):
    today = date.today()
    a = 0
    drugs = Drug.objects.all()
    for drug in drugs:
        if drug.expiry_date <= today:
            a += 1

    context = {
        'expired': a,
        'staff': Staffs.objects.all(),
        'drugs': Drug.objects.filter(visible=True),
        'sale': ItemSale.objects.all(),
        'user': get_user(request.user),
    }
    return render(request, 'base/default_page.html', context)


@login_required(login_url='/?next=/')
def add_employee(request):
    user = get_user(request.user)
    if not user.is_admin:
        return redirect('/not-found')

    form = EmployeeForm(request.POST or None)
    if form.is_valid():
        if form.is_valid():
            name = form.cleaned_data['name']
            sex = form.cleaned_data['sex']
            statue = form.cleaned_data['statue']
            date_of_birth = form.cleaned_data['date_of_birth']
            nationality = form.cleaned_data['nationality']
            address = form.cleaned_data['address']
            phone = form.cleaned_data['phone']
            email = form.cleaned_data['email']
            date_employed = form.cleaned_data['date_employed']
            Employee.objects.create(
                name=name, sex=sex,
                statue=statue, email=email,
                date_of_birth=date_of_birth,
                phone=phone, nationality=nationality,
                address=address,
                date_employed=date_employed
            )
            return redirect("/view-staff")
    context = {
        "form": form,
        'user': get_user(request.user),
    }
    return render(request, 'staff/employee.html', context)


@login_required(login_url='/?next=/')
def registered_staff(request):
    user = get_user(request.user)
    if not user.is_admin:
        return redirect('/not-found')
    staff = Staffs.objects.all()
    context = {
        'staffs': staff,
        'user': user,
    }
    return render(request, 'staff/registered_staff.html', context)


@login_required(login_url='/?next=/')
def view_staff(request):
    user = get_user(request.user)
    if not user.is_admin:
        return redirect('/not-found')

    context = {
        'employees': Employee.objects.all(),
        'user': get_user(request.user),
    }
    return render(request, 'staff/view_staff.html', context)


def not_found(request):
    context = {
        'employees': Employee.objects.all(),
        'user': get_user(request.user),
    }
    return render(request, '404.html', context)


@login_required(login_url='/?next=/')
def delete(request, key):
    user = get_user(request.user)
    if not user.is_admin:
        return redirect('/not-found')
    employee = get_object_or_404(Employee, id=key)
    employee.visible = False
    employee.save()
    context = {
        'employees': Employee.objects.all(),
        'user': get_user(request.user),
    }
    return render(request, 'staff/view_staff.html', context)

templates/staff/employee.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %}Add Employee{% endblock %}

{% block stylesheets %}
    {{ block.super }}    <!-- Ionicons -->

    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />

{% endblock stylesheets %}


{% block right_coln %}
<div class="content-wrapper"><!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Add New Employee </h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="box box-primary">
          <!-- form start -->
          <form role="form" method="post">{% csrf_token %}
              {% for field in form %}
                  <div class="alert-warning">
                  {% if field.errors %}
                    {{ field.label}}  {{ field.errors }}
                  {% endif %}
                  </div>
              {% endfor %}
          <div class="box-body">
              <div class="form-group col-md-6">
                  <label for="fname">Full Name</label>
                  {{ form.name | add_class:"form-control" | attr:'placeholder:Full Name' | append_attr:'id:fname' }}
              </div>
              <div class="form-group col-md-3">
              <label for="passport">Upload Your Passport</label>
              <input type="file" id="passport">
            </div>
              <div class="form-group col-md-3">
                  <label for="sex">Sex</label>
                      {{ form.sex | add_class:"form-control"}}
              </div>
              <div class="form-group col-md-6">
                  <label for="status">Status</label>
                      {{ form.statue | add_class:"form-control" }}
              </div>
              <div class="form-group col-md-6">
                  <label for="dob">DOB</label>
                  {{ form.date_of_birth | add_class:"form-control" | attr:'placeholder:yyyy-mm-dd' | append_attr:'id:dob' }}
              </div>
              <div class="form-group col-md-6">
                  <label for="nation">Nationality</label>
                  {{ form.nationality | add_class:"form-control" | attr:'placeholder:Nationality' | append_attr:'id:nation' }}
              </div>
              <div class="form-group col-md-6">
                  <label for="add">Address</label>
                  {{ form.address | add_class:"form-control" | attr:'rows:3' | append_attr:'id:add' }}
              </div>
              <div class="form-group col-md-6">
                  <label for="phone">Phone Number</label>
                  {{ form.phone | add_class:"form-control" | attr:'placeholder:Phone Number' | append_attr:'id:phone' }}
              </div>
              <div class="form-group col-md-6">
                  <label for="email">Email address</label>
                  {{ form.email | add_class:"form-control" | attr:'placeholder:Email' | append_attr:'id:email' }}
              </div>
              <div class="form-group col-md-12">
                  <label for="date">Date Employed</label>
                  {{ form.date_employed | add_class:"form-control" | attr:'placeholder:Date Employed' | append_attr:'id:date' }}
              <br/><br/>
              </div>
          </div><!-- /.box-body -->
          <div class="box-footer" align="center">
            <button type="submit" class="btn btn-primary">Submit</button>
              <button type="reset" class="btn btn-primary">Restart</button>
          </div>
        </form>
      </div><!-- /.box -->

    </div><!--/.col (left) -->
  </div>   <!-- /.row -->
</section><!-- /.content -->
</div>
{% endblock right_coln %}


{% block javascripts %}
    {{ block.super }}
    <!-- FastClick -->
    <script src='{% static 'plugins/fastclick/fastclick.min.js' %}'></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}" type="text/javascript"></script>


{% endblock javascripts %}

templates/staff/registered_staff.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}Registered Staff{% endblock %}

{% block stylesheets %}
    {{ block.super }}
    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- DATA TABLES -->
    <link href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}" rel="stylesheet" type="text/css" />

    <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
    <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />

{% endblock %}

{% block right_coln %}
  <!-- Right side column. Contains the nav bar and content of the page -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>List of Registered Staff and their Details </h1>
    </section>

    <div class="box">
      <div class="box-body">

          <table id="example1" class="table table-bordered table-striped">
          <thead>
          <tr>
                <td>Full Name</td>
                <td>Username</td>
                <td>Rank</td>
                <td>Last Login</td>
          </tr>
          </thead>
          {% for staff in staffs %}
          <tbody>
          <tr>
                <td>
                    {% if  staff.user.first_name %}
                        {{ staff.user.first_name }} {{ staff.user.last_name }}
                    {% else %}
                        Nil
                    {% endif %}

                    </td>
                <td> {{ staff.user.username }}</td>
                <td>
                  {% if  staff.is_admin %}
                        Admin
                    {% else %}
                        Staff
                    {% endif %}
                </td>
                <td>{{ staff.user.last_login }}</td>
          </tr>
          </tbody>
          {% endfor %}
              <tfoot>
          </tfoot>
        </table>

      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div>
{% endblock right_coln %}
{% block javascripts %}
    {{ block.super }}

    <!-- DATA TABES SCRIPT -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.js' %}" type="text/javascript"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.js' %}" type="text/javascript"></script>
    <!-- SlimScroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='{% static 'plugins/fastclick/fastclick.min.js' %}'></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}" type="text/javascript"></script>
    <!-- page script -->
    <script type="text/javascript">
      $(function () {
        $("#example1").dataTable();
        $('#example2').dataTable({
          "bPaginate": true,
          "bLengthChange": false,
          "bFilter": false,
          "bSort": true,
          "bInfo": true,
          "bAutoWidth": false
        });
      });
    </script>

{% endblock javascripts %}

templates/staff/view_staff.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block title %}View Staff{% endblock title %}
{% block stylesheets %}
    {{ block.super }}
<!-- Ionicons -->
  <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
  <!-- DATA TABLES -->
  <link href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block right_coln %}
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>All Staff Information with their Details</h1>
    </section>

    <div class="box">
      <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
          <tr>
            <td>Full Name</td>
            <td>Sex</td>
            <td>Passport</td>
            <td>Status</td>
            <td>Date of Birth</td>
            <td>Nationality</td>
            <td>Address</td>
            <td>Phone NUmber</td>
            <td>Email</td>
            <td>Date of Employee</td>
            <td>Action</td>
          </tr>
          </thead>
          <tbody>
          {% for employee in employees %}
              {% if employee.visible %}
                  <tr>
                    <td>{{ employee.name }}</td>
                    <td>{{ employee.sex }}</td>
                    <td>Passport</td>
                    <td>{{ employee.statue }}</td>
                    <td>{{ employee.date_of_birth }}</td>
                    <td>{{ employee.nationality }}</td>
                    <td>{{ employee.address }}</td>
                    <td>{{ employee.phone }}</td>
                    <td>{{ employee.email }}</td>
                    <td>{{ employee.date_employed }}</td>
                    <td><a href="{% url 'staff:delete' employee.id %}"> <button  type="button">Delete</button></a></td>
                  </tr>
              {% endif %}
          {% endfor %}
          </tbody>
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div><!-- /.col -->
{% endblock right_coln %}

{% block javascripts %}
    {{ block.super }}
    <!-- DATA TABES SCRIPT -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.js' %}" type="text/javascript"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.js' %}" type="text/javascript"></script>
    <!-- SlimScroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
    <!-- FastClick -->
    <script src="{% static 'plugins/fastclick/fastclick.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}" type="text/javascript"></script>
    <!-- page script -->
    <script type="text/javascript">
      $(function () {
        $("#example1").dataTable();
        $('#example2').dataTable({
          "bPaginate": true,
          "bLengthChange": false,
          "bFilter": false,
          "bSort": true,
          "bInfo": true,
          "bAutoWidth": false
        });
      });
    </script>
{% endblock javascripts %}