cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove')
]

pharmacy/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('staff.urls', namespace='staff')),
    url(r'^sale/', include('sale.urls', namespace='sale')),
    url(r'^drug/', include('drug.urls', namespace='drug')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
]

sale/urls.py
from django.conf.urls import url
from views import (
    view_sale,
    sale_detail,
    sale,
    GeneratePDF
)

urlpatterns = [
    url(r'^$', sale,  name='sale'),
    url(r'^view/$', view_sale, name='view_sale'),
    url(r'^(?P<order>\d+).pdf/$', GeneratePDF.as_view(), name='pdf'),
    url(r'^(?P<key>\d+)/$', sale_detail, name='sale_detail'),
]

sale/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from drug.models import Drug


# Create your models here.
class ItemSale(models.Model):
    customer = models.CharField(max_length=100)
    phone = models.IntegerField(default=0)
    total_pay = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'ItemSale {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class Sale(models.Model):
    item = models.ForeignKey(ItemSale, related_name='items')
    product = models.ForeignKey(Drug, related_name='order_items')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

sale/forms.py
from django import forms
from sale.models import ItemSale


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = ItemSale
        fields = [
            'customer',
            'phone',
        ]

sale/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
    get_list_or_404,
    HttpResponseRedirect,
)
from django.urls import reverse

from cart.cart import Cart
from cart.forms import AddProductForm
from sale.forms import OrderCreateForm
from sale.models import Sale
from drug.models import Drug
from utils import get_user
from django.http import HttpResponse
from django.views.generic import View
from utils import render_to_pdf
import datetime
from django.template.loader import get_template


# Create your views here.
def sale_detail(request, key):
    product = get_object_or_404(Drug, id=key)
    form = AddProductForm()
    context = {
        'product': product,
        'form': form
    }
    return render(request, 'sale/detail.html', context)


@login_required(login_url='/?next=/')
def sale(request):
    form = OrderCreateForm(request.POST or None)
    cart = Cart(request)
    if form.is_valid():
        order = form.save()
        for item in cart:
            Sale.objects.create(
                order=order,
                product=item['product'],
                price=item['price'],
                quantity=item['quantity']
            )
        # clear the cart
        cart.cart.clear()
        cart.save()
        return HttpResponseRedirect(reverse('sale:view_sale'))
    for item in cart:
        item['update_quantity_form'] = AddProductForm(
            initial={
                'quantity': item['quantity'],
                'update': True
            }
        )
    context = {
        'products': Drug.objects.filter(visible=True),
        'user': get_user(request.user),
        'cart': cart,
        'form': form,
    }
    return render(request, 'sale/sales.html', context)


@login_required(login_url='/?next=/')
def view_sale(request):
    user = get_user(request.user)
    if not user.is_admin:
        return redirect('/not-found')
    context = {
        'sales': Sale.objects.all(),
        'user': get_user(request.user),
        }
    return render(request, 'sale/view_sales.html', context)


class GeneratePdf(View):
    def get(self, request, *args, **kwargs):
        data = {
            'today': datetime.date.today(),
            'amount': 39.99,
            'customer': 'Cooper Mann',
            'order_id': 1233434,
        }
        pdf = render_to_pdf('pdf.html', data)
        return HttpResponse(pdf, content_type='application/pdf')


class GeneratePDF(View):
    def get(self, request, order, *args, **kwargs):
        template = get_template('sale/invoice-print.html')
        invoice_value = get_list_or_404(Sale, order_id=order)
        instance = invoice_value[0]
        total = 0
        for invoice_val in invoice_value:
            total += invoice_val.get_cost()
        context = {
            'today': instance.order.created,
            'invoice_values': invoice_value,
            'order_id': order,
            'total': total,
            'instance': instance,
            'invoice_id': str('AJZ' + order + 'R1'),
        }
        template.render(context)
        pdf = render_to_pdf('sale/invoice-print.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Invoice_%s.pdf" % str('000' + order)
            content = "inline; filename='%s'" % filename
            download = self.request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" % filename
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")

templates/sale/detail.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block stylesheets %}
    {{ block.super }}
    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{% static 'dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block right_coln %}
    <div class="content-wrapper">
        <h2>
            <a href="{{ product.category.get_absolute_url }}"><<< Back</a>
        </h2>
        <h1>{{ product.drug_name }}</h1>
        <p class="price">Price: ${{ product.price_per_item }}</p>

    <form action="{% url "cart:cart_add" product.id %}" method="post">
        {{ form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
    </form>
</div>

{% endblock %}


{% block javascripts %}
    {{ block.super }}
    <!-- FastClick -->
    <script src='{% static 'plugins/fastclick/fastclick.min.js' %}'></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}" type="text/javascript"></script>
{% endblock %}

templates/sale/invoice-print.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Invoice</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="{% static '/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{% static 'dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

<body onload="window.print();">

<div class="wrapper" align="center">
    <section class="invoice">
        <div class="row invoice-info">
          <div class="col-sm-4 invoice-col">
              <address>
                <small class="pull-right">Date: {{ today }}<br/>Time: {{ today|time }}</small><br/>
                  <strong>MUJAHID PHARMACY AND STORE.</strong><br>
                  Opp. Asibin murtala<br>
                  Phone: +2348138164746<br/>
                  Email: contact@gmail.com
              </address>
              To:  &nbsp;{{ instance.order.customer }}<br>
              Phone:  &nbsp;{{ instance.order.phone }}<br/>
              Invoice:  &nbsp;{{ invoice_id }}<br/>
              Order ID:  &nbsp;{{ order_id }}<br/>
          </div><br/>
        </div>
        <div class="row">
          <div class="col-xs-12 table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th align="right">Qty</th>
                  <th>Product</th>
                  <th align="left">Price</th>
                  <th align="left">Subtotal</th>
                </tr>
              </thead>
              <tbody>
              {% for invoice_value in invoice_values %}
                  <tr>
                    <td align="right">{{ invoice_value.quantity }}</td>
                    <td>{{ invoice_value.product }}</td>
                    <td align="left">{{ invoice_value.price }}</td>
                    <td align="left">{{ invoice_value.get_cost }}</td>
                  </tr>
              {% endfor %}
              </tbody>
            </table>
          </div><!-- /.col -->
        </div><!-- /.row --><br/>
        <div class="row">
            <div class="col-xs-6">
            <div class="table-responsive">
              <table class="table">
                  <tr>
                      <td align="right">Total:&nbsp;&nbsp;</td>
                      <td align="left">{{ total }}</td>
                </tr>
              </table>
            </div>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </section>
</div>
<script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>

</body>
</html>

templates/sale/sales.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}


{% block stylesheets %}
    {{ block.super }}
    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{% static 'dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block right_coln %}
    <div class="content-wrapper">
        <section class="invoice">
            <div class="row">
                <div class="col-xs-12">
                    <h2 class="page-header">
                        <small class="pull-right">Date: 2/10/2014</small>
                    </h2>
                </div>
            </div>
            <div class="row invoice-info">
                <div class="col-sm-4 invoice-col">From
                    <address>
                        <strong>MUJAHID PHARMACY AND STORE.</strong><br>
                        Opp. Asibin murtala<br>
                        Phone: +2348138164746<br/>
                        Email: contact@gmail.com
                    </address>
                </div>
                <div class="col-sm-4 invoice-col">
                    <form role="form" method="post" action=".">{% csrf_token %}
                        <div class="form-group">
                            <label for="cname">To</label>
                            {{ form.customer | add_class:"form-control" | attr:'placeholder:Customer Name' | append_attr:'id:cname' }}
                        </div>
                        <div class="form-group">
                            <label for="cphone">Phone Number</label>
                            {{ form.phone | add_class:"form-control" | attr:'placeholder:Phone Number' | append_attr:'id:cphone' }}
                        </div>
                        <button type="submit" class="btn btn-primary">Finished</button>
                    </form>

                </div>
                <div class="row">
                    <div class="col-xs-4 table-responsive">
                        <div class="box-body">
                            <div class="form-group">
                            <label>All Product</label><br>
                                {% for product in products %}
                                    <a href="{% url 'sale:sale_detail' product.id  %} ">
                                    {{ product.drug_name }}
                                    </a>₦{{ product.price_per_item }}<br/>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row no-print">
                    <div class="col-xs-12">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Remove</th>
                        <th>Subtotal</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                          {% for item in cart %}
                            {% with product=item.product %}
                            <tr>
                                <td>{{ product.drug_name }}</td>
                                <td>
                                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                                        {{ item.update_quantity_form.quantity }}
                                        {{ item.update_quantity_form.update }}
                                        <input type="submit" value="Update">
                                        {% csrf_token %}
                                    </form>
                                </td>
                                <td class="num">${{ item.price }}</td>
                                <td class="num"><a href="{% url "cart:cart_remove" product.id %}"> Remove</a></td>
                                <td class="num">${{ item.total_price }}</td>
                            </tr>
                        {% endwith %}
                            {% endfor %}
                        {% else %}
                            Your cart is empty
                        {% endif %}
                    {% endwith %}
                    </tbody>
                </table>
                <table class="table">
                    <tr>
                        <td>Total</td>
                        <td>₦{{ cart.get_total_price }}</td>
                    </tr>
                </table>
            </div>

                </div>
            </div>
        </section>
    </div>
{% endblock %}

{% block javascripts %}
    {{ block.super }}
    <!-- FastClick -->
    <script src='{% static 'plugins/fastclick/fastclick.min.js' %}'></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}" type="text/javascript"></script>
{% endblock %}

templates/sale/view_sales.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block stylesheets %}
    {{ block.super }}

<!-- Ionicons -->
  <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
  <!-- DATA TABLES -->
  <link href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
  <!-- Theme style -->
  <link href="{% static 'dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}


{% block right_coln %}


  <!-- Right side column. Contains the navbar and content of the page -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Data Tables
        <small>advanced tables</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Data tables</li>
      </ol>
    </section>

    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Data of drug that have been sold</h3>
      </div><!-- /.box-header -->
      <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
          <tr>
            <td>Customer Name</td>
            <td>Phone Number</td>
            <td>Product</td>
            <td>Quantity</td>
            <td>Order</td>
            <td>Price per item</td>
            <td>Total</td>
            <td>Print</td>
          </tr>
          </thead>
          <tbody>
          {% for sale in sales %}
              <tr>
                <td>{{ sale.order.customer }}</td>
                <td>{{ sale.order.phone }}</td>
                <td>{{ sale.product }}</td>
                <td>{{ sale.quantity }}</td>
                <td>{{ sale.order }}</td>
                <td>{{ sale.price }}</td>
                <td>{{ sale.get_cost }}</td>
                <td>
                    <a href="{% url 'sale:pdf' sale.id  %}" target="_blank" class="btn btn-default"><i class="fa fa-print"></i>
                        Print
                    </a>
              </tr>
          {% endfor %}
          </tbody>
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
</div><!-- ./wrapper -->
{% endblock %}

{% block javascripts %}
    {{ block.super }}
    <!-- DATA TABES SCRIPT -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.js' %}" type="text/javascript"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.js' %}" type="text/javascript"></script>
    <!-- SlimScroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js'%}" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='{% static 'plugins/fastclick/fastclick.min.js' %}'></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js'%}" type="text/javascript"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js'%}" type="text/javascript"></script>
    <!-- page script -->
    <script type="text/javascript">
      $(function () {
        $("#example1").dataTable();
        $('#example2').dataTable({
          "bPaginate": true,
          "bLengthChange": false,
          "bFilter": false,
          "bSort": true,
          "bInfo": true,
          "bAutoWidth": false
        });
      });
    </script>

{% endblock %}